name: Deploy to WordPress.org
on:
  push:
    branches:
    - "main"
jobs:
  tag:
    name: New release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@main
    - name: Build
      run: |
        npm install
        npm run build
    - name: WordPress Plugin Deploy
      id: deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      with:
        generate-zip: true
      env:
        SVN_PASSWORD: ${{ secrets.WP_SVN_PASS }}
        SVN_USERNAME: ${{ secrets.WP_SVN_USER }}
        SLUG: talash
