name: Deploy to WordPress.org
on:
  push:
    branches:
    - "main"
jobs:
  tag:
    name: New release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@main
    - name: Build
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm install
    - run: npm run build
    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_PASSWORD: ${{ secrets.WP_SVN_PASS }}
        SVN_USERNAME: ${{ secrets.WP_SVN_USER }}
        SLUG: talash
